### ISSUE TITLE
нейминг

### ISSUE THREAD

**Issue by igorosors** [k1poO/prof_soft_24#1]
https://github.com/k1poO/prof_soft_24/blob/b2f00fc7c54fe5a215b351341ff7c71f568ac327/lesson1/app/src/main/res/layout/activity_first.xml#L14

лучше использовать полное название вьюх: button, text_view, edit_text
Если в верстке их будет много, нейминг по типу tv, et, btn будет неудобным и плохо читаемым

**Comment by k1poO** [comment]
Исправил
